// Generated by CoffeeScript 1.10.0
var VariableGenerator;

VariableGenerator = (function() {
  function VariableGenerator() {}

  VariableGenerator.generate = function(params) {
    var count, expanded, expanded_length, header, header_list, headers, headers_n, i, j, key, n, path, path_list, path_n, ref, ref1, ref2, value, var_name;
    path_list = [];
    header_list = [];
    path = params.request.path;
    headers = params.request.headers;
    count = Math.min(params.pattern.end, 1000);
    expanded = {};
    expanded_length = 0;
    ref = params.variables;
    for (key in ref) {
      value = ref[key];
      switch (value.type) {
        case 'list':
          expanded[key] = value.entries;
          expanded_length = value.entries.length;
          break;
        case 'alpha':
          expanded[key] = (function() {
            var j, ref1, results;
            results = [];
            for (n = j = 1, ref1 = count; 1 <= ref1 ? j <= ref1 : j >= ref1; n = 1 <= ref1 ? ++j : --j) {
              results.push(this.random_alpha(value.min, value.max));
            }
            return results;
          }).call(this);
          break;
        case 'number':
          expanded[key] = (function() {
            var j, ref1, results;
            results = [];
            for (n = j = 1, ref1 = count; 1 <= ref1 ? j <= ref1 : j >= ref1; n = 1 <= ref1 ? ++j : --j) {
              results.push(this.random_integer(value.min, value.max));
            }
            return results;
          }).call(this);
          break;
        case 'uuid':
          console.log("NOT IMPLEMENTED: uuid");
      }
    }
    if (expanded_length === 0) {
      expanded_length = count;
    }
    for (i = j = 0, ref1 = expanded_length - 1; 0 <= ref1 ? j <= ref1 : j >= ref1; i = 0 <= ref1 ? ++j : --j) {
      path_n = path;
      headers_n = {};
      ref2 = params.variables;
      for (var_name in ref2) {
        value = ref2[var_name];
        path_n = path_n.replace(RegExp("\\#\\{" + var_name + "\\}", "g"), expanded[var_name][i]);
        for (header in headers) {
          value = headers[header];
          headers_n[header] = value.replace(RegExp("\\#\\{" + var_name + "\\}", "g"), expanded[var_name][i]);
        }
      }
      path_list.push(path_n);
      header_list.push(headers_n);
    }
    return [path_list, header_list];
  };

  VariableGenerator.random_alpha = function(min, max) {
    var charSet, j, n, ref, word;
    charSet = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ';
    word = "";
    for (n = j = 1, ref = (Math.random() * (max - min)) + min; 1 <= ref ? j <= ref : j >= ref; n = 1 <= ref ? ++j : --j) {
      word += charSet[Math.floor(Math.random() * charSet.length)];
    }
    return word;
  };

  VariableGenerator.random_integer = function(min, max) {
    max = parseInt(max, 10);
    min = parseInt(min, 10);
    return Math.floor(Math.random() * (max - min)) + min;
  };

  return VariableGenerator;

})();

module.exports = VariableGenerator;
